### PR TITLE
Support dimod<0.13

### PR DESCRIPTION
**Pull request by arcondello**

### CODE REVIEW

**Comment by arcondello** [comment]
Looks like the `pip install . -c` doesn't like the release candidate dimod. I can not do the constrained install. Or I can just not test with that dimod for now (I did test locally and all works fine)

**Review by randomir — COMMENTED** [review]
Code changes look good, but we should fix the CI before merging. Looks like pip resolver tries to build greedy 0.2.1, which uses numpy 1.19.4 that doesn't support py310. Perhaps introducing additional constraints in the rc tests would help?

**Comment by arcondello** [comment]
That's only an error in the 3.10.0 one. In the others it's the constrained pip install. E.g. https://app.circleci.com/pipelines/github/dwavesystems/dwave-hybrid/529/workflows/cd5a9511-a160-4803-8696-e4b2696ba6cb/jobs/5539

**Comment by randomir** [comment]
Looks like waiting helped :laughing: 

Not sure what changed, but all tests pass now. Perhaps newer pip handles rc properly?

**Comment by arcondello** [comment]
Huh. Well good!

**Review by randomir — APPROVED** [review]

**Pull request merged**
